name: CMake

on:
  pull_request:
    branches: [ trunk ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Cahce conan
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
          #TODO: this will not grap a new version when it comes out
        key: ${{ runner.os }}-pip-conan-1.38
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configure conan
      if: steps.cache-conan.outputs.cache-hit != 'true'
      run: pip3 install conan; conan -v


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DENABLE_SANITIZER_ADDRESS=ON
        -DENABLE_SANITIZER_LEAK=ON
        -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
        -DENABLE_DOXYGEN=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

