name: CMake

on:
  pull_request:
    branches: [ trunk ]

env:
  # cmake
  BUILD_TYPE: Release

  # conan
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

  # lcov
  LCOV_VERSION: 1.15


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64


    - name: Set up lcov
      run: |
        mkdir Iconv
        cd Iconv
        wget "https://github.com/linux-test-project/lcov/releases/download/v$LCOV_VERSION/lcov-$LCOV_VERSION.tar.gz"
        tar -xzf "lcov-$LCOV_VERSION.tar.gz"
        cd "lcov-$LCOV_VERSION"
        sudo make install


    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-modules
      with:
        path: |
          ${{ env.CONAN_USER_HOME }}
          ~/.cache/pip
        key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('cmake/Conan.cmake') }}


    - name: Configure conan
      run: pip3 install conan; conan -v


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DENABLE_SANITIZER_ADDRESS=ON
        -DENABLE_SANITIZER_LEAK=ON
        -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
        -DENABLE_COVERAGE=ON
        -DENABLE_CPPCHECK=OFF
        -DENABLE_CLANG_TIDY=OFF
        -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
        -DENABLE_CACHE=OFF
        -DENABLE_DOXYGEN=OFF


    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}


    - name: Coverage
      working-directory: ${{github.workspace}}/build
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '*conan/*' --output-file coverage.info


    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: .
        env_vars: OS
        files: ./coverage.info
        path_to_write_report: ./codecov_report.txt
        verbose: true

